from typing import Type

from example import Circle, Shape, Square, SwigPyObject

class CvarInterface:
    Shape_nshapes: int

cvar: CvarInterface

################################################################################
#
# Shape
#
################################################################################
def Shape_swigregister(self: Type[Shape]) -> None: ...
def delete_Shape(self: Shape) -> None: ...

def Shape_x_set(self: Shape, x: float) -> None: ...
def Shape_x_get(self: Shape) -> float: ...
def Shape_y_set(self: Shape, y: float) -> None: ...
def Shape_y_get(self: Shape) -> float: ...
def Shape_move(self: Shape, dx: float, dy: float) -> None: ...
def Shape_area(self: Shape) -> float: ...
def Shape_perimeter(self: Shape) -> float: ...
def Shape_nshapes_get(self: Shape) -> int: ...
def Shape_nshapes_set(self: Shape, nshapes: int) -> None: ...

################################################################################
#
# Circle
#
################################################################################
def Circle_swigregister(self: Type[Circle]) -> None: ...
def Circle_swiginit(self: Circle, allocator: SwigPyObject) -> None: ...
def new_Circle(r: float) -> SwigPyObject: ...
def delete_Circle(self: Circle) -> None: ...

def Circle_area(self: Circle) -> float: ...
def Circle_perimeter(self: Circle) -> float: ...

################################################################################
#
# Square
#
################################################################################
def Square_swigregister(self: Type[Square]) -> None: ...
def Square_swiginit(self: Square, allocator: SwigPyObject) -> None: ...
def new_Square(w: float) -> SwigPyObject: ...
def delete_Square(self: Square) -> None: ...

def Square_area(self: Square) -> float: ...
def Square_perimeter(self: Square) -> float: ...
